all: Executables
	gcc shell.c -lreadline
	./a.out
	
Executables: date cat mkdir rm ls

date:
	gcc date.c -o date

cat:
	gcc cat.c -o cat

mkdir:
	gcc mkdir.c -o mkdir

rm:
	gcc rm.c -o rm

ls: 
	gcc ls.c -o ls