all : C_Compilation Asm_Compilation1 
	gcc P4.o add.o -o a.out
	./a.out

C_Compilation:Object

Object:
	gcc -c P4.c -o P4.o

Asm_Compilation1: 
	nasm -f elf64 P4_2.asm -o add.o

	
	
	
	
	
	
	
	
	
	
	
	


 
